grafana:
  enabled: true

  adminUser: admin

  service:
    type: ClusterIP

  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    storageClassName: openebs-hostpath

prometheus:
  enabled: true

  prometheusSpec:
    retention: 7d

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true

defaultRules:
  create: true
