apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail

      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos

      tag kubernetes.*
      read_from_head true

      <parse>
        @type cri
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match kubernetes.**>
      @type loki

      url "http://loki.logging.svc.cluster.local:3100"

      <label>
        job kubernetes
        namespace_name $.kubernetes.namespace_name
        pod_name $.kubernetes.pod_name
        container_name $.kubernetes.container_name
      </label>

      line_format json
    </match>
